spring:
  application:
    name: Value-Demo
    environment: dev

  datasource:
    #url: jdbc:postgresql://host.docker.internal:5432/postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
# debug: true

logging:
  level:
    org.springframework.boot.autoconfigure: INFO
    #org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.web.method.annotation: INFO

notification:
  email:
    enabled : false
    from-address: test@gmail.com

  sms:
    enabled : true
    sender-id: "codesnippet"

  retry:
    max-attempts: 3
    backoff-milisec: 500



  endpoints:
    web:
      exposure:
        include: actuators,health,info
