spring:
  application:
    name: Value-Demo
    environment: dev

# debug: true

logging:
  level:
    org.springframework.boot.autoconfigure: INFO
    #org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.web.method.annotation: INFO

notification:
  email:
    enabled : false
    from-address: test@gmail.com

  sms:
    enabled : true
    sender-id: "codesnippet"

  retry:
    max-attempts: 3
    backoff-milisec: 500



  endpoints:
    web:
      exposure:
        include: actuators,health,info
